version: '3'

services:
  web:
    build: ..
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/code
    ports:
    - "8000:8000"
    depends_on:
      - database

  database:
    image: mysql:5.7.28
    environment:
      MYSQL_DATABASE: 'beerproject'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
    - "3308:3308"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
