# Generated by Django 2.1.7 on 2019-12-19 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Beers',
                'db_table': 'beers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Breweries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Breweries',
                'db_table': 'breweries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_mod', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Geocodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.CharField(max_length=255)),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='breweries.Breweries')),
            ],
            options={
                'verbose_name_plural': 'Geocodes',
                'db_table': 'geocodes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=255)),
                ('last_mod', models.DateField()),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='breweries.Categories')),
            ],
            options={
                'verbose_name_plural': 'Styles',
                'db_table': 'styles',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='beers',
            name='brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='breweries.Breweries'),
        ),
    ]
