# Generated by Django 2.1.7 on 2019-12-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breweries', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
