# Generated by Django 2.1.7 on 2019-12-17 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breweries', '0002_delete_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('last_mod', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=200)),
                ('last_mod', models.DateTimeField()),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breweries.Categories')),
            ],
        ),
    ]
